version: '3.9'
services:
  springboot-server:
    image: motel
    container_name: springboot-server
    ports:
      - "8080:8080"
    depends_on:
      - database
      - redis
    environment:
      - DATASOURCE_URL=jdbc:mysql://database:3306/motel_manager_db
      - DATASOURCE_USERNAME=user
      - DATASOURCE_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
      - MINIO_BUCKET_NAME=motel-bucket
      - JWT_SECRET=${JWT_SECRET}
      - SMS_PROVIDER=${SMS_PROVIDER:test}
      - INFOBIP_API_KEY=${INFOBIP_API_KEY}
      - INFOBIP_BASE_URL=${INFOBIP_BASE_URL}
      - STORAGE_PROVIDER=${STORAGE_PROVIDER:minio}
      - FIREBASE_SERVICE_ACCOUNT_KEY_PATH=${FIREBASE_SERVICE_ACCOUNT_KEY_PATH}
      - PUSH_NOTIFICATION_PROVIDER=${PUSH_NOTIFICATION_PROVIDER:fcm}
    volumes:
      - ./storage:/app/storage
      
  database:
    image: mysql:8.0
    container_name: mysql-database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: motel_manager_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  db_data:
  storage:
  minio_data: